// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hiroaki-yamamoto/reusable-services/adapter (interfaces: IAdapter)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	adapter "github.com/hiroaki-yamamoto/reusable-services/adapter"
	reflect "reflect"
)

// MockIAdapter is a mock of IAdapter interface
type MockIAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockIAdapterMockRecorder
}

// MockIAdapterMockRecorder is the mock recorder for MockIAdapter
type MockIAdapterMockRecorder struct {
	mock *MockIAdapter
}

// NewMockIAdapter creates a new mock instance
func NewMockIAdapter(ctrl *gomock.Controller) *MockIAdapter {
	mock := &MockIAdapter{ctrl: ctrl}
	mock.recorder = &MockIAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIAdapter) EXPECT() *MockIAdapterMockRecorder {
	return m.recorder
}

// Delete mocks base method
func (m *MockIAdapter) Delete(arg0 context.Context, arg1 interface{}) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *MockIAdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIAdapter)(nil).Delete), arg0, arg1)
}

// DeleteMany mocks base method
func (m *MockIAdapter) DeleteMany(arg0 context.Context, arg1 interface{}) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMany", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMany indicates an expected call of DeleteMany
func (mr *MockIAdapterMockRecorder) DeleteMany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMany", reflect.TypeOf((*MockIAdapter)(nil).DeleteMany), arg0, arg1)
}

// Find mocks base method
func (m *MockIAdapter) Find(arg0 context.Context, arg1, arg2 interface{}, arg3 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Find indicates an expected call of Find
func (mr *MockIAdapterMockRecorder) Find(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIAdapter)(nil).Find), varargs...)
}

// FindOne mocks base method
func (m *MockIAdapter) FindOne(arg0 context.Context, arg1, arg2 interface{}, arg3 ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindOne indicates an expected call of FindOne
func (mr *MockIAdapterMockRecorder) FindOne(arg0, arg1, arg2 interface{}, arg3 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIAdapter)(nil).FindOne), varargs...)
}

// Insert mocks base method
func (m *MockIAdapter) Insert(arg0 context.Context, arg1 interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockIAdapterMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIAdapter)(nil).Insert), arg0, arg1)
}

// InsertMany mocks base method
func (m *MockIAdapter) InsertMany(arg0 context.Context, arg1 []interface{}) ([]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", arg0, arg1)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMany indicates an expected call of InsertMany
func (mr *MockIAdapterMockRecorder) InsertMany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockIAdapter)(nil).InsertMany), arg0, arg1)
}

// Update mocks base method
func (m *MockIAdapter) Update(arg0 context.Context, arg1, arg2 interface{}) (*adapter.UpdateSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*adapter.UpdateSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockIAdapterMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIAdapter)(nil).Update), arg0, arg1, arg2)
}

// UpdateMany mocks base method
func (m *MockIAdapter) UpdateMany(arg0 context.Context, arg1, arg2 interface{}) (*adapter.UpdateSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMany", arg0, arg1, arg2)
	ret0, _ := ret[0].(*adapter.UpdateSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMany indicates an expected call of UpdateMany
func (mr *MockIAdapterMockRecorder) UpdateMany(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMany", reflect.TypeOf((*MockIAdapter)(nil).UpdateMany), arg0, arg1, arg2)
}
