version: "3.7"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: adapter
      MONGO_INITDB_ROOT_PASSWORD: adapter
    tmpfs:
      - /data/db
  adapter-db-mongo:
    build:
      context: .
      args:
        PKGNAME: adapter/db/mongodb
    volumes:
      - ".:/opt/code"
    depends_on:
      - mongo
  email:
    build:
      context: .
      args:
        PKGNAME: email
    volumes:
      - ".:/opt/code"
  render:
    build:
      context: .
      args:
        PKGNAME: render/go
    volumes:
      - ".:/opt/code"
  render-python:
    build:
      context: ./render/py
    volumes:
      - "./render/py:/opt/code"
  token:
    build:
      context: .
      args:
        PKGNAME: token
    volumes:
      - ".:/opt/code"
  random:
    build:
      context: .
      args:
        PKGNAME: random
    volumes:
      - ".:/opt/code"
