version: "3.7"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: adapter
      MONGO_INITDB_ROOT_PASSWORD: adapter
    tmpfs:
      - /data/db
  token:
    build:
      context: .
      args:
        PKGNAME: token
    volumes:
      - ".:/opt/code"
  adapter-db-mongo:
    build:
      context: .
      args:
        PKGNAME: adapter/db/mongodb
    volumes:
      - ".:/opt/code"
    depends_on:
      - mongo
  random:
    build:
      context: .
      args:
        PKGNAME: random
    volumes:
      - ".:/opt/code"
