// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Pw                   string   `protobuf:"bytes,4,opt,name=pw,proto3" json:"pw,omitempty"`
	PwConfirm            string   `protobuf:"bytes,5,opt,name=pwConfirm,proto3" json:"pwConfirm,omitempty"`
	IsActive             bool     `protobuf:"varint,6,opt,name=isActive,proto3" json:"isActive,omitempty"`
	LockReason           string   `protobuf:"bytes,7,opt,name=lockReason,proto3" json:"lockReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthInfo) Reset()         { *m = AuthInfo{} }
func (m *AuthInfo) String() string { return proto.CompactTextString(m) }
func (*AuthInfo) ProtoMessage()    {}
func (*AuthInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *AuthInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthInfo.Unmarshal(m, b)
}
func (m *AuthInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthInfo.Marshal(b, m, deterministic)
}
func (m *AuthInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthInfo.Merge(m, src)
}
func (m *AuthInfo) XXX_Size() int {
	return xxx_messageInfo_AuthInfo.Size(m)
}
func (m *AuthInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthInfo proto.InternalMessageInfo

func (m *AuthInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AuthInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthInfo) GetPw() string {
	if m != nil {
		return m.Pw
	}
	return ""
}

func (m *AuthInfo) GetPwConfirm() string {
	if m != nil {
		return m.PwConfirm
	}
	return ""
}

func (m *AuthInfo) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *AuthInfo) GetLockReason() string {
	if m != nil {
		return m.LockReason
	}
	return ""
}

type AccessToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthInfo)(nil), "auth.models.AuthInfo")
	proto.RegisterType((*AccessToken)(nil), "auth.models.AccessToken")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x94, 0x94, 0xf4, 0x8a, 0x18, 0x2c, 0x06, 0x0b, 0x21, 0x54, 0x95, 0xa5, 0x53,
	0x17, 0x9e, 0x20, 0x30, 0xb1, 0x30, 0x44, 0x4c, 0x6c, 0xc6, 0xb9, 0xaa, 0x56, 0x62, 0x9f, 0x65,
	0x3b, 0xe4, 0xcd, 0x78, 0x3e, 0x64, 0x1b, 0x85, 0x6e, 0xf7, 0x7d, 0xa7, 0xfb, 0xf5, 0x1f, 0xdc,
	0x18, 0xea, 0x71, 0x0c, 0x47, 0xe7, 0x29, 0x12, 0xdf, 0xca, 0x29, 0x9e, 0x8f, 0x45, 0xed, 0x7f,
	0x18, 0x34, 0xed, 0x14, 0xcf, 0x6f, 0xf6, 0x44, 0xfc, 0x16, 0x2a, 0xdd, 0x0b, 0xb6, 0x63, 0x87,
	0x4d, 0x57, 0xe9, 0x9e, 0xdf, 0x43, 0x33, 0x05, 0xf4, 0xef, 0xd2, 0xa0, 0xa8, 0xb2, 0x5d, 0x98,
	0xdf, 0x41, 0x8d, 0x46, 0xea, 0x51, 0xac, 0xf2, 0xa2, 0x40, 0x4a, 0x70, 0xb3, 0xb8, 0x2a, 0x09,
	0x6e, 0xe6, 0x0f, 0xb0, 0x71, 0xf3, 0x2b, 0xd9, 0x93, 0xf6, 0x46, 0xd4, 0x59, 0xff, 0x8b, 0x94,
	0xaf, 0x43, 0xab, 0xa2, 0xfe, 0x46, 0xb1, 0xde, 0xb1, 0x43, 0xd3, 0x2d, 0xcc, 0x1f, 0x01, 0x46,
	0x52, 0x43, 0x87, 0x32, 0x90, 0x15, 0xd7, 0xf9, 0xf4, 0xc2, 0xec, 0x9f, 0x60, 0xdb, 0x2a, 0x85,
	0x21, 0x7c, 0xd0, 0x80, 0x36, 0xd5, 0x89, 0x69, 0xf8, 0x6b, 0x5f, 0xe0, 0xa5, 0xfe, 0x5c, 0x79,
	0xa7, 0xbe, 0xd6, 0xf9, 0xf1, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xac, 0x8c, 0xaa, 0x68,
	0x08, 0x01, 0x00, 0x00,
}
