// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Otp                  string   `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetOtp() string {
	if m != nil {
		return m.Otp
	}
	return ""
}

type CredentialChangeRequest1 struct {
	Token                *AccessToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Current              string       `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CredentialChangeRequest1) Reset()         { *m = CredentialChangeRequest1{} }
func (m *CredentialChangeRequest1) String() string { return proto.CompactTextString(m) }
func (*CredentialChangeRequest1) ProtoMessage()    {}
func (*CredentialChangeRequest1) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *CredentialChangeRequest1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialChangeRequest1.Unmarshal(m, b)
}
func (m *CredentialChangeRequest1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialChangeRequest1.Marshal(b, m, deterministic)
}
func (m *CredentialChangeRequest1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialChangeRequest1.Merge(m, src)
}
func (m *CredentialChangeRequest1) XXX_Size() int {
	return xxx_messageInfo_CredentialChangeRequest1.Size(m)
}
func (m *CredentialChangeRequest1) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialChangeRequest1.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialChangeRequest1 proto.InternalMessageInfo

func (m *CredentialChangeRequest1) GetToken() *AccessToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *CredentialChangeRequest1) GetCurrent() string {
	if m != nil {
		return m.Current
	}
	return ""
}

type CredentialChangeRequest2 struct {
	LoginToken           *AccessToken `protobuf:"bytes,1,opt,name=loginToken,proto3" json:"loginToken,omitempty"`
	Token                string       `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Current              string       `protobuf:"bytes,3,opt,name=current,proto3" json:"current,omitempty"`
	New                  string       `protobuf:"bytes,4,opt,name=new,proto3" json:"new,omitempty"`
	Confirm              string       `protobuf:"bytes,5,opt,name=confirm,proto3" json:"confirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CredentialChangeRequest2) Reset()         { *m = CredentialChangeRequest2{} }
func (m *CredentialChangeRequest2) String() string { return proto.CompactTextString(m) }
func (*CredentialChangeRequest2) ProtoMessage()    {}
func (*CredentialChangeRequest2) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *CredentialChangeRequest2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialChangeRequest2.Unmarshal(m, b)
}
func (m *CredentialChangeRequest2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialChangeRequest2.Marshal(b, m, deterministic)
}
func (m *CredentialChangeRequest2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialChangeRequest2.Merge(m, src)
}
func (m *CredentialChangeRequest2) XXX_Size() int {
	return xxx_messageInfo_CredentialChangeRequest2.Size(m)
}
func (m *CredentialChangeRequest2) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialChangeRequest2.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialChangeRequest2 proto.InternalMessageInfo

func (m *CredentialChangeRequest2) GetLoginToken() *AccessToken {
	if m != nil {
		return m.LoginToken
	}
	return nil
}

func (m *CredentialChangeRequest2) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CredentialChangeRequest2) GetCurrent() string {
	if m != nil {
		return m.Current
	}
	return ""
}

func (m *CredentialChangeRequest2) GetNew() string {
	if m != nil {
		return m.New
	}
	return ""
}

func (m *CredentialChangeRequest2) GetConfirm() string {
	if m != nil {
		return m.Confirm
	}
	return ""
}

type ReminerRequest1 struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReminerRequest1) Reset()         { *m = ReminerRequest1{} }
func (m *ReminerRequest1) String() string { return proto.CompactTextString(m) }
func (*ReminerRequest1) ProtoMessage()    {}
func (*ReminerRequest1) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *ReminerRequest1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReminerRequest1.Unmarshal(m, b)
}
func (m *ReminerRequest1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReminerRequest1.Marshal(b, m, deterministic)
}
func (m *ReminerRequest1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReminerRequest1.Merge(m, src)
}
func (m *ReminerRequest1) XXX_Size() int {
	return xxx_messageInfo_ReminerRequest1.Size(m)
}
func (m *ReminerRequest1) XXX_DiscardUnknown() {
	xxx_messageInfo_ReminerRequest1.DiscardUnknown(m)
}

var xxx_messageInfo_ReminerRequest1 proto.InternalMessageInfo

func (m *ReminerRequest1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ReminerRequest2 struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	New                  string   `protobuf:"bytes,3,opt,name=new,proto3" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReminerRequest2) Reset()         { *m = ReminerRequest2{} }
func (m *ReminerRequest2) String() string { return proto.CompactTextString(m) }
func (*ReminerRequest2) ProtoMessage()    {}
func (*ReminerRequest2) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *ReminerRequest2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReminerRequest2.Unmarshal(m, b)
}
func (m *ReminerRequest2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReminerRequest2.Marshal(b, m, deterministic)
}
func (m *ReminerRequest2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReminerRequest2.Merge(m, src)
}
func (m *ReminerRequest2) XXX_Size() int {
	return xxx_messageInfo_ReminerRequest2.Size(m)
}
func (m *ReminerRequest2) XXX_DiscardUnknown() {
	xxx_messageInfo_ReminerRequest2.DiscardUnknown(m)
}

var xxx_messageInfo_ReminerRequest2 proto.InternalMessageInfo

func (m *ReminerRequest2) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReminerRequest2) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReminerRequest2) GetNew() string {
	if m != nil {
		return m.New
	}
	return ""
}

type UserExistence struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Exists               bool     `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserExistence) Reset()         { *m = UserExistence{} }
func (m *UserExistence) String() string { return proto.CompactTextString(m) }
func (*UserExistence) ProtoMessage()    {}
func (*UserExistence) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{5}
}

func (m *UserExistence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserExistence.Unmarshal(m, b)
}
func (m *UserExistence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserExistence.Marshal(b, m, deterministic)
}
func (m *UserExistence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserExistence.Merge(m, src)
}
func (m *UserExistence) XXX_Size() int {
	return xxx_messageInfo_UserExistence.Size(m)
}
func (m *UserExistence) XXX_DiscardUnknown() {
	xxx_messageInfo_UserExistence.DiscardUnknown(m)
}

var xxx_messageInfo_UserExistence proto.InternalMessageInfo

func (m *UserExistence) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserExistence) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type ActivationRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivationRequest) Reset()         { *m = ActivationRequest{} }
func (m *ActivationRequest) String() string { return proto.CompactTextString(m) }
func (*ActivationRequest) ProtoMessage()    {}
func (*ActivationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{6}
}

func (m *ActivationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivationRequest.Unmarshal(m, b)
}
func (m *ActivationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivationRequest.Marshal(b, m, deterministic)
}
func (m *ActivationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivationRequest.Merge(m, src)
}
func (m *ActivationRequest) XXX_Size() int {
	return xxx_messageInfo_ActivationRequest.Size(m)
}
func (m *ActivationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivationRequest proto.InternalMessageInfo

func (m *ActivationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
	proto.RegisterType((*CredentialChangeRequest1)(nil), "CredentialChangeRequest1")
	proto.RegisterType((*CredentialChangeRequest2)(nil), "CredentialChangeRequest2")
	proto.RegisterType((*ReminerRequest1)(nil), "ReminerRequest1")
	proto.RegisterType((*ReminerRequest2)(nil), "ReminerRequest2")
	proto.RegisterType((*UserExistence)(nil), "UserExistence")
	proto.RegisterType((*ActivationRequest)(nil), "ActivationRequest")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xd5, 0x75, 0x2d, 0xdd, 0xe9, 0x68, 0x87, 0xb5, 0x4d, 0x21, 0xdc, 0xa0, 0xdc, 0x00,
	0x37, 0x9e, 0x56, 0x24, 0xe0, 0x06, 0x44, 0x29, 0x15, 0x82, 0x0b, 0x56, 0x55, 0xad, 0x2a, 0x71,
	0x97, 0xb9, 0xa7, 0x49, 0xb4, 0xc4, 0x0e, 0xb6, 0xb3, 0xc2, 0x5b, 0xf1, 0x0a, 0xbc, 0x19, 0x4a,
	0xec, 0x84, 0x76, 0x5b, 0x26, 0xe8, 0x5d, 0x4e, 0xce, 0x9f, 0xef, 0xe7, 0xe3, 0xcf, 0xd0, 0x53,
	0x28, 0xaf, 0x23, 0x86, 0x8a, 0xa6, 0x52, 0x68, 0xe1, 0x3e, 0x09, 0x84, 0x08, 0x62, 0x3c, 0x2b,
	0xa2, 0xcb, 0x6c, 0x75, 0x86, 0x49, 0xaa, 0x7f, 0xda, 0xe4, 0x61, 0x22, 0x96, 0x18, 0xdb, 0x52,
	0x6f, 0x01, 0xdd, 0x61, 0xa6, 0xc3, 0x29, 0x7e, 0xcf, 0x50, 0x69, 0xe2, 0x42, 0x27, 0x53, 0x28,
	0xbf, 0xfa, 0x09, 0x3a, 0x8d, 0xa7, 0x8d, 0xe7, 0x07, 0xd3, 0x2a, 0xce, 0x73, 0xa9, 0xaf, 0xd4,
	0x5a, 0xc8, 0xa5, 0xb3, 0x67, 0x72, 0x65, 0x4c, 0x8e, 0xa0, 0x29, 0x74, 0xea, 0x34, 0x8b, 0xdf,
	0xf9, 0xa7, 0xb7, 0x04, 0x67, 0x24, 0x71, 0x89, 0x5c, 0x47, 0x7e, 0x3c, 0x0a, 0x7d, 0x1e, 0xa0,
	0x15, 0x39, 0x27, 0x14, 0x5a, 0x5a, 0x5c, 0x21, 0x2f, 0x24, 0xba, 0x03, 0x87, 0xfa, 0x99, 0x0e,
	0xa9, 0xe5, 0x1a, 0x32, 0x86, 0x4a, 0xcd, 0xf2, 0xfc, 0xd4, 0x94, 0x11, 0x07, 0x1e, 0xb0, 0x4c,
	0x4a, 0xe4, 0xda, 0x0a, 0x97, 0xa1, 0xf7, 0xab, 0x51, 0x2b, 0x33, 0x20, 0x6f, 0x00, 0x62, 0x11,
	0x44, 0x7c, 0xf6, 0x4f, 0x5a, 0x1b, 0xb5, 0xe4, 0xb8, 0x04, 0x34, 0x72, 0xb7, 0x31, 0x9a, 0x5b,
	0x18, 0xf9, 0xf1, 0x39, 0xae, 0x9d, 0x7d, 0x73, 0x7c, 0x8e, 0xeb, 0xa2, 0x56, 0xf0, 0x55, 0x24,
	0x13, 0xa7, 0x65, 0x6b, 0x4d, 0xe8, 0x3d, 0x83, 0xfe, 0x14, 0x93, 0x88, 0xa3, 0xac, 0xf6, 0x71,
	0x0c, 0x2d, 0x4c, 0xfc, 0x28, 0xb6, 0x2b, 0x37, 0x81, 0x77, 0x71, 0xb3, 0x70, 0xf0, 0x97, 0xab,
	0xb1, 0xc9, 0x55, 0xb5, 0xef, 0x6d, 0xb4, 0x97, 0x4c, 0xcd, 0x8a, 0xc9, 0x1b, 0xc1, 0xc3, 0xb9,
	0x42, 0x39, 0xfe, 0x11, 0x29, 0x8d, 0x9c, 0xe1, 0xbd, 0xb7, 0x7d, 0x0a, 0x6d, 0xcc, 0x0b, 0x55,
	0x31, 0xb5, 0x33, 0xb5, 0x91, 0xf7, 0x02, 0x1e, 0x0d, 0x99, 0x8e, 0xae, 0x7d, 0x1d, 0x09, 0x5e,
	0xda, 0xe6, 0x4e, 0xae, 0xc1, 0xef, 0x36, 0xec, 0xe7, 0xe6, 0x22, 0xaf, 0xa1, 0xad, 0xa2, 0x80,
	0xcf, 0x53, 0x72, 0xb2, 0xbd, 0xfe, 0x4c, 0x87, 0x9f, 0xf9, 0x4a, 0xb8, 0xa7, 0xd4, 0x38, 0x96,
	0x96, 0x8e, 0xa5, 0xe3, 0xdc, 0xb1, 0xe4, 0x15, 0x74, 0x7c, 0x23, 0x86, 0x84, 0xd0, 0x5b, 0xba,
	0xb5, 0x7d, 0xef, 0xa0, 0x1b, 0xa0, 0x2e, 0xc7, 0x93, 0xda, 0x4b, 0x77, 0xef, 0xe6, 0x21, 0xe7,
	0xd0, 0x67, 0x21, 0xb2, 0xab, 0x6a, 0x5d, 0x8a, 0xf4, 0xe8, 0xd6, 0xee, 0xdc, 0x1b, 0x31, 0xa1,
	0xb0, 0x9f, 0x8f, 0x22, 0x87, 0x74, 0xe3, 0x3d, 0xb9, 0xb5, 0xca, 0xe4, 0x13, 0x10, 0x69, 0x8a,
	0xc6, 0xf9, 0x75, 0x19, 0xeb, 0x92, 0xc7, 0xb4, 0xee, 0xd1, 0xd4, 0x9e, 0xf5, 0x3d, 0x74, 0x59,
	0xe8, 0x27, 0x01, 0x16, 0x73, 0xea, 0x27, 0x0c, 0x6a, 0x27, 0x7c, 0x84, 0xbe, 0x45, 0x99, 0x2c,
	0x76, 0xe7, 0x78, 0x0b, 0x1d, 0xc3, 0x31, 0x59, 0xec, 0x02, 0xf1, 0x05, 0x4e, 0x2c, 0xc4, 0xdc,
	0x5a, 0x70, 0x77, 0x94, 0x11, 0xf4, 0x0c, 0x4a, 0x39, 0x6a, 0xb7, 0xad, 0x1c, 0x59, 0x20, 0xd3,
	0x70, 0x31, 0x9b, 0xdc, 0x63, 0xa4, 0x7a, 0x27, 0x1e, 0xb0, 0xaa, 0xfd, 0xff, 0x29, 0x3e, 0xb4,
	0xbe, 0x35, 0x65, 0xca, 0x2e, 0xdb, 0xc5, 0xef, 0x97, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5b,
	0x53, 0xc7, 0xc7, 0xea, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	SignUp(ctx context.Context, in *AuthInfo, opts ...grpc.CallOption) (*empty.Empty, error)
	Activate(ctx context.Context, in *ActivationRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetAuthInfo(ctx context.Context, in *AccessToken, opts ...grpc.CallOption) (*AuthInfo, error)
	CheckUserExists(ctx context.Context, in *UserExistence, opts ...grpc.CallOption) (*UserExistence, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AccessToken, error)
	RequestEmailChange(ctx context.Context, in *CredentialChangeRequest1, opts ...grpc.CallOption) (*empty.Empty, error)
	ChamgeEmail(ctx context.Context, in *CredentialChangeRequest2, opts ...grpc.CallOption) (*empty.Empty, error)
	RequestPWChange(ctx context.Context, in *CredentialChangeRequest1, opts ...grpc.CallOption) (*empty.Empty, error)
	ChamgePW(ctx context.Context, in *CredentialChangeRequest2, opts ...grpc.CallOption) (*empty.Empty, error)
	RequestUserNameChange(ctx context.Context, in *CredentialChangeRequest1, opts ...grpc.CallOption) (*empty.Empty, error)
	ChamgeUserName(ctx context.Context, in *CredentialChangeRequest2, opts ...grpc.CallOption) (*empty.Empty, error)
	RequestChangeOTP(ctx context.Context, in *AccessToken, opts ...grpc.CallOption) (*empty.Empty, error)
	ChangeOTP(ctx context.Context, in *CredentialChangeRequest2, opts ...grpc.CallOption) (*empty.Empty, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) SignUp(ctx context.Context, in *AuthInfo, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/signUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Activate(ctx context.Context, in *ActivationRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/activate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetAuthInfo(ctx context.Context, in *AccessToken, opts ...grpc.CallOption) (*AuthInfo, error) {
	out := new(AuthInfo)
	err := c.cc.Invoke(ctx, "/Auth/getAuthInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CheckUserExists(ctx context.Context, in *UserExistence, opts ...grpc.CallOption) (*UserExistence, error) {
	out := new(UserExistence)
	err := c.cc.Invoke(ctx, "/Auth/checkUserExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AccessToken, error) {
	out := new(AccessToken)
	err := c.cc.Invoke(ctx, "/Auth/auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RequestEmailChange(ctx context.Context, in *CredentialChangeRequest1, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/requestEmailChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ChamgeEmail(ctx context.Context, in *CredentialChangeRequest2, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/chamgeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RequestPWChange(ctx context.Context, in *CredentialChangeRequest1, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/requestPWChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ChamgePW(ctx context.Context, in *CredentialChangeRequest2, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/chamgePW", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RequestUserNameChange(ctx context.Context, in *CredentialChangeRequest1, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/requestUserNameChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ChamgeUserName(ctx context.Context, in *CredentialChangeRequest2, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/chamgeUserName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RequestChangeOTP(ctx context.Context, in *AccessToken, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/requestChangeOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ChangeOTP(ctx context.Context, in *CredentialChangeRequest2, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Auth/changeOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	SignUp(context.Context, *AuthInfo) (*empty.Empty, error)
	Activate(context.Context, *ActivationRequest) (*empty.Empty, error)
	GetAuthInfo(context.Context, *AccessToken) (*AuthInfo, error)
	CheckUserExists(context.Context, *UserExistence) (*UserExistence, error)
	Auth(context.Context, *AuthRequest) (*AccessToken, error)
	RequestEmailChange(context.Context, *CredentialChangeRequest1) (*empty.Empty, error)
	ChamgeEmail(context.Context, *CredentialChangeRequest2) (*empty.Empty, error)
	RequestPWChange(context.Context, *CredentialChangeRequest1) (*empty.Empty, error)
	ChamgePW(context.Context, *CredentialChangeRequest2) (*empty.Empty, error)
	RequestUserNameChange(context.Context, *CredentialChangeRequest1) (*empty.Empty, error)
	ChamgeUserName(context.Context, *CredentialChangeRequest2) (*empty.Empty, error)
	RequestChangeOTP(context.Context, *AccessToken) (*empty.Empty, error)
	ChangeOTP(context.Context, *CredentialChangeRequest2) (*empty.Empty, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) SignUp(ctx context.Context, req *AuthInfo) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedAuthServer) Activate(ctx context.Context, req *ActivationRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Activate not implemented")
}
func (*UnimplementedAuthServer) GetAuthInfo(ctx context.Context, req *AccessToken) (*AuthInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthInfo not implemented")
}
func (*UnimplementedAuthServer) CheckUserExists(ctx context.Context, req *UserExistence) (*UserExistence, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserExists not implemented")
}
func (*UnimplementedAuthServer) Auth(ctx context.Context, req *AuthRequest) (*AccessToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedAuthServer) RequestEmailChange(ctx context.Context, req *CredentialChangeRequest1) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestEmailChange not implemented")
}
func (*UnimplementedAuthServer) ChamgeEmail(ctx context.Context, req *CredentialChangeRequest2) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChamgeEmail not implemented")
}
func (*UnimplementedAuthServer) RequestPWChange(ctx context.Context, req *CredentialChangeRequest1) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPWChange not implemented")
}
func (*UnimplementedAuthServer) ChamgePW(ctx context.Context, req *CredentialChangeRequest2) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChamgePW not implemented")
}
func (*UnimplementedAuthServer) RequestUserNameChange(ctx context.Context, req *CredentialChangeRequest1) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUserNameChange not implemented")
}
func (*UnimplementedAuthServer) ChamgeUserName(ctx context.Context, req *CredentialChangeRequest2) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChamgeUserName not implemented")
}
func (*UnimplementedAuthServer) RequestChangeOTP(ctx context.Context, req *AccessToken) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestChangeOTP not implemented")
}
func (*UnimplementedAuthServer) ChangeOTP(ctx context.Context, req *CredentialChangeRequest2) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeOTP not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SignUp(ctx, req.(*AuthInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Activate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Activate(ctx, req.(*ActivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/GetAuthInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetAuthInfo(ctx, req.(*AccessToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_CheckUserExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserExistence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CheckUserExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/CheckUserExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CheckUserExists(ctx, req.(*UserExistence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RequestEmailChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialChangeRequest1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RequestEmailChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/RequestEmailChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RequestEmailChange(ctx, req.(*CredentialChangeRequest1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ChamgeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialChangeRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ChamgeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/ChamgeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ChamgeEmail(ctx, req.(*CredentialChangeRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RequestPWChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialChangeRequest1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RequestPWChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/RequestPWChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RequestPWChange(ctx, req.(*CredentialChangeRequest1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ChamgePW_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialChangeRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ChamgePW(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/ChamgePW",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ChamgePW(ctx, req.(*CredentialChangeRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RequestUserNameChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialChangeRequest1)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RequestUserNameChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/RequestUserNameChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RequestUserNameChange(ctx, req.(*CredentialChangeRequest1))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ChamgeUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialChangeRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ChamgeUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/ChamgeUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ChamgeUserName(ctx, req.(*CredentialChangeRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RequestChangeOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RequestChangeOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/RequestChangeOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RequestChangeOTP(ctx, req.(*AccessToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ChangeOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialChangeRequest2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ChangeOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/ChangeOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ChangeOTP(ctx, req.(*CredentialChangeRequest2))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "signUp",
			Handler:    _Auth_SignUp_Handler,
		},
		{
			MethodName: "activate",
			Handler:    _Auth_Activate_Handler,
		},
		{
			MethodName: "getAuthInfo",
			Handler:    _Auth_GetAuthInfo_Handler,
		},
		{
			MethodName: "checkUserExists",
			Handler:    _Auth_CheckUserExists_Handler,
		},
		{
			MethodName: "auth",
			Handler:    _Auth_Auth_Handler,
		},
		{
			MethodName: "requestEmailChange",
			Handler:    _Auth_RequestEmailChange_Handler,
		},
		{
			MethodName: "chamgeEmail",
			Handler:    _Auth_ChamgeEmail_Handler,
		},
		{
			MethodName: "requestPWChange",
			Handler:    _Auth_RequestPWChange_Handler,
		},
		{
			MethodName: "chamgePW",
			Handler:    _Auth_ChamgePW_Handler,
		},
		{
			MethodName: "requestUserNameChange",
			Handler:    _Auth_RequestUserNameChange_Handler,
		},
		{
			MethodName: "chamgeUserName",
			Handler:    _Auth_ChamgeUserName_Handler,
		},
		{
			MethodName: "requestChangeOTP",
			Handler:    _Auth_RequestChangeOTP_Handler,
		},
		{
			MethodName: "changeOTP",
			Handler:    _Auth_ChangeOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
