// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Purpose              string   `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Meta                 []byte   `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *Token) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*Token)(nil), "token.models.Token")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x29, 0xc9, 0xcf, 0x4e, 0xcd, 0xd3, 0x03,
	0x0b, 0x15, 0x2b, 0x25, 0x72, 0xb1, 0x86, 0x80, 0xf8, 0x42, 0x22, 0x5c, 0xac, 0xa9, 0xb9, 0x89,
	0x99, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x0e, 0x48, 0x14, 0xac, 0x5c, 0x82,
	0x09, 0x22, 0x0a, 0xe6, 0x08, 0x49, 0x70, 0xb1, 0x17, 0x94, 0x16, 0x15, 0xe4, 0x17, 0xa7, 0x4a,
	0x30, 0x83, 0xc5, 0x61, 0x5c, 0x21, 0x21, 0x2e, 0x96, 0xdc, 0xd4, 0x92, 0x44, 0x09, 0x16, 0x05,
	0x46, 0x0d, 0x9e, 0x20, 0x30, 0xdb, 0x49, 0x3d, 0x4a, 0x35, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49,
	0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x23, 0xb3, 0x28, 0x3f, 0x31, 0x3b, 0x53, 0xb7, 0x32, 0x31, 0x37,
	0x31, 0x37, 0xbf, 0x24, 0x5f, 0x1f, 0x6c, 0xa4, 0x7e, 0x51, 0x41, 0x72, 0x12, 0x1b, 0xd8, 0x81,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xf7, 0x8b, 0x2e, 0xaf, 0x00, 0x00, 0x00,
}
