// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CleanupResult struct {
	NumDeleteToken       int64    `protobuf:"varint,1,opt,name=num_delete_token,json=numDeleteToken,proto3" json:"num_delete_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanupResult) Reset()         { *m = CleanupResult{} }
func (m *CleanupResult) String() string { return proto.CompactTextString(m) }
func (*CleanupResult) ProtoMessage()    {}
func (*CleanupResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *CleanupResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanupResult.Unmarshal(m, b)
}
func (m *CleanupResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanupResult.Marshal(b, m, deterministic)
}
func (m *CleanupResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanupResult.Merge(m, src)
}
func (m *CleanupResult) XXX_Size() int {
	return xxx_messageInfo_CleanupResult.Size(m)
}
func (m *CleanupResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanupResult.DiscardUnknown(m)
}

var xxx_messageInfo_CleanupResult proto.InternalMessageInfo

func (m *CleanupResult) GetNumDeleteToken() int64 {
	if m != nil {
		return m.NumDeleteToken
	}
	return 0
}

func init() {
	proto.RegisterType((*CleanupResult)(nil), "token.CleanupResult")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xc9, 0xcf, 0x4e, 0xcd,
	0x93, 0xe2, 0xce, 0xcd, 0x4f, 0x49, 0xcd, 0x81, 0x88, 0x29, 0x59, 0x72, 0xf1, 0x3a, 0xe7, 0xa4,
	0x26, 0xe6, 0x95, 0x16, 0x04, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x08, 0x69, 0x70, 0x09, 0xe4, 0x95,
	0xe6, 0xc6, 0xa7, 0xa4, 0xe6, 0xa4, 0x96, 0xa4, 0xc6, 0x83, 0x75, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x30, 0x07, 0xf1, 0xe5, 0x95, 0xe6, 0xba, 0x80, 0x85, 0x43, 0x40, 0xa2, 0x46, 0x59, 0x5c, 0xac,
	0x60, 0x86, 0x90, 0x01, 0x17, 0x4b, 0x40, 0x69, 0x71, 0x86, 0x90, 0xb0, 0x1e, 0x58, 0xb9, 0x1e,
	0xd8, 0xfc, 0x62, 0x3d, 0xb0, 0xa4, 0x14, 0x36, 0x41, 0x21, 0x7d, 0x2e, 0xe6, 0x80, 0xfc, 0x02,
	0xe2, 0x35, 0x38, 0xb1, 0x46, 0x31, 0x17, 0x15, 0x24, 0x27, 0xb1, 0x81, 0x1d, 0x6d, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xad, 0x89, 0x99, 0xa6, 0xd9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenClient is the client API for Token service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenClient interface {
	Push(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
	Pop(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
}

type tokenClient struct {
	cc *grpc.ClientConn
}

func NewTokenClient(cc *grpc.ClientConn) TokenClient {
	return &tokenClient{cc}
}

func (c *tokenClient) Push(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/token.Token/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) Pop(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/token.Token/Pop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServer is the server API for Token service.
type TokenServer interface {
	Push(context.Context, *Token) (*Token, error)
	Pop(context.Context, *Token) (*Token, error)
}

// UnimplementedTokenServer can be embedded to have forward compatible implementations.
type UnimplementedTokenServer struct {
}

func (*UnimplementedTokenServer) Push(ctx context.Context, req *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (*UnimplementedTokenServer) Pop(ctx context.Context, req *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pop not implemented")
}

func RegisterTokenServer(s *grpc.Server, srv TokenServer) {
	s.RegisterService(&_Token_serviceDesc, srv)
}

func _Token_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.Token/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).Push(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_Pop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).Pop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.Token/Pop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).Pop(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

var _Token_serviceDesc = grpc.ServiceDesc{
	ServiceName: "token.Token",
	HandlerType: (*TokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Token_Push_Handler,
		},
		{
			MethodName: "Pop",
			Handler:    _Token_Pop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
