// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RenderingRequest struct {
	// Template rendering data
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// argument data encoded with MessagePack
	// Note, this field is passed as "keyword arguments" to the template.
	ArgumentMap          []byte   `protobuf:"bytes,2,opt,name=argumentMap,proto3" json:"argumentMap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderingRequest) Reset()         { *m = RenderingRequest{} }
func (m *RenderingRequest) String() string { return proto.CompactTextString(m) }
func (*RenderingRequest) ProtoMessage()    {}
func (*RenderingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{0}
}

func (m *RenderingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderingRequest.Unmarshal(m, b)
}
func (m *RenderingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderingRequest.Marshal(b, m, deterministic)
}
func (m *RenderingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderingRequest.Merge(m, src)
}
func (m *RenderingRequest) XXX_Size() int {
	return xxx_messageInfo_RenderingRequest.Size(m)
}
func (m *RenderingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderingRequest proto.InternalMessageInfo

func (m *RenderingRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *RenderingRequest) GetArgumentMap() []byte {
	if m != nil {
		return m.ArgumentMap
	}
	return nil
}

type RenderingResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderingResponse) Reset()         { *m = RenderingResponse{} }
func (m *RenderingResponse) String() string { return proto.CompactTextString(m) }
func (*RenderingResponse) ProtoMessage()    {}
func (*RenderingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b5431a010549573, []int{1}
}

func (m *RenderingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderingResponse.Unmarshal(m, b)
}
func (m *RenderingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderingResponse.Marshal(b, m, deterministic)
}
func (m *RenderingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderingResponse.Merge(m, src)
}
func (m *RenderingResponse) XXX_Size() int {
	return xxx_messageInfo_RenderingResponse.Size(m)
}
func (m *RenderingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderingResponse proto.InternalMessageInfo

func (m *RenderingResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*RenderingRequest)(nil), "render.RenderingRequest")
	proto.RegisterType((*RenderingResponse)(nil), "render.RenderingResponse")
}

func init() { proto.RegisterFile("models.proto", fileDescriptor_0b5431a010549573) }

var fileDescriptor_0b5431a010549573 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcd, 0x4f, 0x49,
	0xcd, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x4a, 0xcd, 0x4b, 0x49, 0x2d,
	0x52, 0xf2, 0xe0, 0x12, 0x08, 0x02, 0xb3, 0x32, 0xf3, 0xd2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b,
	0x4b, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0xc0, 0x6c, 0x21, 0x05, 0x2e, 0xee, 0xc4, 0xa2, 0xf4, 0xd2, 0xdc, 0xd4, 0xbc, 0x12, 0xdf, 0xc4,
	0x02, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x64, 0x21, 0x25, 0x75, 0x2e, 0x41, 0x24, 0x93,
	0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xb1, 0x19, 0xe5, 0xa4, 0x11, 0xa5, 0x96, 0x9e, 0x59, 0x92,
	0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x91, 0x59, 0x94, 0x9f, 0x98, 0x9d, 0xa9, 0x5b,
	0x99, 0x98, 0x9b, 0x98, 0x9b, 0x5f, 0x92, 0xaf, 0x0f, 0x71, 0x98, 0x7e, 0x51, 0x41, 0x72, 0x12,
	0x1b, 0xd8, 0xad, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x02, 0x9e, 0x75, 0xbb, 0x00,
	0x00, 0x00,
}
