# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import models_pb2 as models__pb2


class TemplateServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.render = channel.unary_unary(
        '/render.TemplateService/render',
        request_serializer=models__pb2.RenderingRequest.SerializeToString,
        response_deserializer=models__pb2.RenderingResponse.FromString,
        )


class TemplateServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def render(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TemplateServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'render': grpc.unary_unary_rpc_method_handler(
          servicer.render,
          request_deserializer=models__pb2.RenderingRequest.FromString,
          response_serializer=models__pb2.RenderingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'render.TemplateService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
